application: eka-oldauth
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /login
  script: main.app
  secure: always
  login: required

- url: /logout
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.1"
